// Copyright 2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by internal/tools/stencil. DO NOT EDIT.

package vm

import (
	"unsafe"
)

func StoreFromScratch32(p1 P1, p2 P2) (P1, P2) {
	_ = StoreFromScratch[uint32]
	var p unsafe.Pointer
	p1, p2, p = getUntypedMutableField(p1, p2)
	*(*uint32)(p) = uint32(p2.Scratch())
	return p1, p2
}
func StoreFromScratch64(p1 P1, p2 P2) (P1, P2) {
	_ = StoreFromScratch[uint64]
	var p unsafe.Pointer
	p1, p2, p = getUntypedMutableField(p1, p2)
	*(*uint64)(p) = uint64(p2.Scratch())
	return p1, p2
}
